### ISSUE TITLE
Error in function BroadcastingLikelihood

### ISSUE THREAD

**Issue by wizmik12** [FelixOpolka/Deep-Gaussian-Process#1]
This function inherits from the class Likelihood. But it raises "can't instantiate abstract class with abstract methods".  It seems that in to inherit from Likelihood Class you have to define some abstracts methods. 

The function BroadcastingLikelihood since is a wrapper of an actual likelihood should work without any inheritance?

**Comment by wizmik12** [comment]
I have some questions about the code. I tried to fix the problems I commented. I tried it with MNIST and step function but the code does not provide reasonable results. Have you been working with it?

**Comment by XiaoyuHy** [comment]
Yes, I'm trying to replicate the code , and  it raises "self.likelihood = BroadcastingLikelihood(likelihood)
TypeError: Can't instantiate abstract class BroadcastingLikelihood with abstract methods _log_prob, _predict_log_density, _predict_mean_and_var, _variational_expectations". 

Just wondered whether anyone has fixed this problem?

**Comment by FelixOpolka** [comment]
Thank you for flagging these issues. It seems I wrote the code when GPFlow 2.0 was still an rc and there were some slight changes. I have updated the code and it should work now with GPFlow 2.0.
