### ISSUE TITLE
Error in function init_layers_linear

### ISSUE THREAD

**Issue by wizmik12** [FelixOpolka/Deep-Gaussian-Process#2]
It raises an error in line 29 of module layer_initializations.py. 

It seems that the way of setting these variables as not trainable is from Tensorflow 1. In Tensorflow 2, I think the way is:

gpflow.set_trainable(mf.A, False)
gpflow.set_trainable(mf.b, False)

**Comment by XiaoyuHy** [comment]
Yes, the above code works for Tensorflow 2.

**Comment by FelixOpolka** [comment]
Thank you for spotting this, I have updated the code.
